/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cust_android_screencap_ScreenCap */

#ifndef _Included_com_cust_android_screencap_ScreenCap
#define _Included_com_cust_android_screencap_ScreenCap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cust_android_screencap_ScreenCap
 * Method:    captureScreenToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cust_android_screencap_ScreenCap_captureScreenToFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
